### PR TITLE
Make the binary less dependent on the build system

### PR DESCRIPTION
**Pull request by jankratochvil**
```
/criu: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
/criu: error while loading shared libraries: libbpf.so.1: cannot open shared object file: No such file or directory
/criu: error while loading shared libraries: libnftables.so.1: cannot open shared object file: No such file or directory
```

### CODE REVIEW

**Review by rvansa — APPROVED** [review]
I think that `libbsd` provides just some helpers, but about `libbpf` and `libnftables`: Have you inspected the code what types of applications would fail to C/R without these?

**Comment by jankratochvil** [comment]
libbpf: Support of dumping a process providing bpf program to kernel. @AntonKozlov had a mail Message-ID: <f4125d33-f784-00e2-6be1-75795d54f79e@azul.com> about using BPF in Java but IIUC it has no future.

libnftables: net namespace can contain also nftables rules so criu can dump+restore them. I do not think that is used for Java.

**Comment by AntonKozlov** [comment]
LGTM. But the problem does not refer to (some) docker image specifically. I propose to change the description to reflect we are giving up optional dependencies regardless do they present on the build system.

**Comment by jankratochvil** [comment]
Still there are some dependencies we do not plan to give up on - such as `libselinux`. At least it does not cause any problems with @rvansa's docker image. I do not run SELinux and I did not explicitly try it but IIUC `libselinux` is required on SELinux-enabled systems.

**Comment by AntonKozlov** [comment]
I took the bravery to update the subject of the PR as it will be recorded in the git history. Please let me know if the new one is OK. Thanks!

**Comment by jankratochvil** [comment]
Yes, sure.

**Pull request merged**
